server:
  port: 8989
spring:
  application:
        name: maxbase-auth

  ureka:
        client:
             defaultZone: http://localhost:8991/eureka

        instance:
            prefer-ip-address: true
            instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}